-- MySQL Script generated by MySQL Workbench
-- Tue Sep 29 17:24:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WhoAmI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WhoAmI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WhoAmI` DEFAULT CHARACTER SET utf8 ;
USE `WhoAmI` ;

-- -----------------------------------------------------
-- Table `WhoAmI`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WhoAmI`.`Game` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `GameString` TEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WhoAmI`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WhoAmI`.`Room` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Game_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Room_Game1_idx` (`Game_ID` ASC),
  CONSTRAINT `fk_Room_Game1`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `WhoAmI`.`Game` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WhoAmI`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WhoAmI`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PlayerType` VARCHAR(50) NOT NULL,
  `Room_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_User_Room1_idx` (`Room_ID` ASC),
  CONSTRAINT `fk_User_Room1`
    FOREIGN KEY (`Room_ID`)
    REFERENCES `WhoAmI`.`Room` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WhoAmI`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WhoAmI`.`Image` (
  `ID` INT NOT NULL,
  `FileName` VARCHAR(50) NOT NULL,
  `Game_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Game_ID`),
  INDEX `fk_Image_Game_idx` (`Game_ID` ASC),
  CONSTRAINT `fk_Image_Game`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `WhoAmI`.`Game` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
